{{- if .Values.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "trufflehog-enterprise"
  labels:
    app.kubernetes.io/name: {{ include "trufflehog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
value: {{ .Values.priorityClass.value }}
description: "Priority class for Trufflehog Enterprise"
{{- end }}
