name: Release Helm charts

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
