name: Sync Labels

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync:
    uses: trufflesecurity/.github/.github/workflows/label-sync-reusable.yml@main
